-- =========================================================
-- BloodLink ColdChain — Full Schema (Supabase / Postgres)
-- Run this whole file in the Supabase SQL Editor.
-- =========================================================

-- 1. HOSPITALS
CREATE TABLE hospitals (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    address TEXT NOT NULL,
    state TEXT NOT NULL,                 -- Nigerian state, e.g. 'Nasarawa'
    lga TEXT,                            -- Local Government Area
    emergency_phone TEXT NOT NULL,
    latitude FLOAT8,
    longitude FLOAT8,
    has_generator_backup BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. BLOOD INVENTORY
CREATE TABLE blood_inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hospital_id UUID REFERENCES hospitals(id) ON DELETE CASCADE NOT NULL,
    blood_type TEXT CHECK (blood_type IN ('A+','A-','B+','B-','AB+','AB-','O+','O-')) NOT NULL,
    units_available INT NOT NULL DEFAULT 0 CHECK (units_available >= 0),
    batch_expiry_date DATE NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER PUBLICATION supabase_realtime ADD TABLE blood_inventory;

-- 3. DONORS (WhatsApp mobilization registry)
CREATE TABLE donors (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    full_name TEXT NOT NULL,
    phone TEXT NOT NULL,                 -- E.164 format, e.g. +2348012345678
    blood_type TEXT CHECK (blood_type IN ('A+','A-','B+','B-','AB+','AB-','O+','O-')) NOT NULL,
    state TEXT NOT NULL,
    lga TEXT,
    last_donated DATE,
    whatsapp_opt_in BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. POWER OUTAGE / COLD-CHAIN RISK LOG
CREATE TABLE outage_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hospital_id UUID REFERENCES hospitals(id) ON DELETE CASCADE NOT NULL,
    start_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    end_time TIMESTAMPTZ,                -- NULL while outage is ongoing
    generator_backup BOOLEAN DEFAULT FALSE,
    notes TEXT
);

ALTER PUBLICATION supabase_realtime ADD TABLE outage_logs;

-- 5. OFFLINE SYNC QUEUE (server-side mirror; client also queues in IndexedDB)
-- Used so the service worker has a stable table shape to replay writes into.
-- (No special replication needed — normal inserts.)

-- =========================================================
-- Row Level Security — kept OPEN for hackathon/demo speed.
-- Tighten before any real production use.
-- =========================================================
ALTER TABLE hospitals ENABLE ROW LEVEL SECURITY;
ALTER TABLE blood_inventory ENABLE ROW LEVEL SECURITY;
ALTER TABLE donors ENABLE ROW LEVEL SECURITY;
ALTER TABLE outage_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "public read hospitals" ON hospitals FOR SELECT USING (true);
CREATE POLICY "public write hospitals" ON hospitals FOR INSERT WITH CHECK (true);
CREATE POLICY "public update hospitals" ON hospitals FOR UPDATE USING (true);

CREATE POLICY "public read inventory" ON blood_inventory FOR SELECT USING (true);
CREATE POLICY "public write inventory" ON blood_inventory FOR INSERT WITH CHECK (true);
CREATE POLICY "public update inventory" ON blood_inventory FOR UPDATE USING (true);
CREATE POLICY "public delete inventory" ON blood_inventory FOR DELETE USING (true);

CREATE POLICY "public read donors" ON donors FOR SELECT USING (true);
CREATE POLICY "public write donors" ON donors FOR INSERT WITH CHECK (true);

CREATE POLICY "public read outages" ON outage_logs FOR SELECT USING (true);
CREATE POLICY "public write outages" ON outage_logs FOR INSERT WITH CHECK (true);
CREATE POLICY "public update outages" ON outage_logs FOR UPDATE USING (true);

-- =========================================================
-- Seed: a few Nigerian states for quick demo dropdowns
-- (Full list is hard-coded in the frontend, this is just sample data)
-- =========================================================
INSERT INTO hospitals (name, address, state, lga, emergency_phone, has_generator_backup)
VALUES
('Federal Medical Centre, Keffi', 'Keffi, Nasarawa State', 'Nasarawa', 'Keffi', '+2348012345678', true),
('Dalhatu Araf Specialist Hospital', 'Lafia, Nasarawa State', 'Nasarawa', 'Lafia', '+2348023456789', false),
('National Hospital Abuja', 'Central Business District, Abuja', 'FCT', 'AMAC', '+2348034567890', true);
